encoding: UTF-8

# Where things are
source              : .
destination         : ./_site
collections_dir     : .
layouts_dir         : _layouts
data_dir            : _data
includes_dir        : _includes
sass:
  sass_dir          : _sass
collections:
  posts:
    output          : true

# Outputting
permalink           : :title
future              : true
defaults:
  - scope:
      path: ""
    values:
      layout: default